export const EMPLOYEE_LIST_REQUEST = 'EMPLOYEE_LIST_REQUEST'
export const EMPLOYEE_LIST_SUCCESS = 'EMPLOYEE_LIST_SUCCESS'
export const EMPLOYEE_LIST_FAIL = 'EMPLOYEE_LIST_FAIL'

// export const SEARCH_LIST_REQUEST = 'SEARCH_LIST_REQUEST'
// export const SEARCH_LIST_SUCCESS = 'SEARCH_LIST_SUCCESS'
// export const SEARCH_LIST_FAIL = 'SEARCH_LIST_FAIL'

